// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import { defineConfig } from 'prisma/config'

const USER = process.env['POSTGRES_USER']
const PASSWORD = process.env['POSTGRES_PASSWORD']
const HOST = process.env['POSTGRES_HOST']
const PORT = process.env['POSTGRES_PORT']
const DB = process.env['POSTGRES_DB']

const DB_URL = `postgresql://${USER}:${PASSWORD}@${HOST}:${PORT}/${DB}?schema=public`

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations'
    },
    datasource: {
        url: DB_URL
    }
})
